#pragma once
#define dt (app.fps.dt())
#define dur (app.fps.dur())
#define scr (app.scr)
#define dscr (app.dscr)
#define vpscr (scr.rect())
#define ft (app.ft)
#define loc (app.loc)

#define msw (app.in.msw)
#define chs (app.in.chs)
#define msp (app.in.msp)
#define msp_old (app.in.msp_old)
#define msd (app.in.msd)
#define msd_old (app.in.msd_old)
#define msnd (!msd[0] && !msd[1] && !msd[2])
#define msc (app.in.msc)
#define kbmsg (app.in.kbmsg)
#define kbd (app.in.kbd)
#define kbd_old (app.in.kbd_old)
#define kbc (app.in.kbc)

#define own (app.own)
#define kb (own.kb)
#define free_kb (own.free_kb)
#define hvd (own.hvd)
#define dhv (own.dhv)
#define whd (own.whd)
#define dwh (own.dwh)
#define rmv own.remove(this);
#define rhvd (hovered && msnd)
